version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper
    container_name: zookeeper
    networks:
      - kafka_network
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka01:
    image: confluentinc/cp-kafka
    container_name: kafka01
    networks:
      - kafka_network
    depends_on:
      - zookeeper
    ports:
      - "8097:8097"
    environment:
      KAFKA_LISTENERS: EXTERNAL_SAME_HOST://:8097,INTERNAL://:9092
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL_SAME_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka01:9092,EXTERNAL_SAME_HOST://localhost:8097
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

  kafka02:
    image: confluentinc/cp-kafka
    container_name: kafka02
    networks:
      - kafka_network
    depends_on:
      - zookeeper
    ports:
      - "8098:8098"
    environment:
      KAFKA_LISTENERS: EXTERNAL_SAME_HOST://:8098,INTERNAL://:9092
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL_SAME_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka02:9092,EXTERNAL_SAME_HOST://localhost:8098
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

  kafka03:
    image: confluentinc/cp-kafka
    container_name: kafka03
    networks:
      - kafka_network
    depends_on:
      - zookeeper
    ports:
      - "8099:8099"
    environment:
      KAFKA_LISTENERS: EXTERNAL_SAME_HOST://:8099,INTERNAL://:9092
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL_SAME_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka03:9092,EXTERNAL_SAME_HOST://localhost:8099
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL


networks:
  kafka_network:
    driver: bridge
