version: '3.8'

services:
    redis:
        image: redis
        container_name: redis
        restart: unless-stopped
        ports:
            - 6379:6379
        networks:
            - redis_net
networks:
    redis_net:
      driver: bridge
